name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          source .venv/bin/activate
          flake8 .

      - name: Run black (check only)
        run: |
          source .venv/bin/activate
          black --check .

      - name: Run mypy
        run: |
          source .venv/bin/activate
          mypy .

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
